#!/bin/bash
export DISPLAY=:0
export SIKULI_HOME=~/Sikuli-X-1.0rc3-linux-x86_64/Sikuli-IDE

#export PATH=/var/lib/jenkins/.rvm/gems/jruby-1.7.19/bin:/var/lib/jenkins/.rvm/gems/jruby-1.7.19@global/bin:/var/lib/jenkins/.rvm/rubies/jruby-1.7.19/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/var/lib/jenkins/.rvm/bin:/var/lib/jenkins/.rvm/bin:/var/lib/jenkins/Sikuli-X-1.0rc3-linux-x86_64/Sikuli-IDE:/var/lib/jenkins/Sikuli-X-1.0rc3-linux-x86_64/Sikuli-IDE/libs

export PATH=$PATH:/var/lib/jenkins/.rvm/bin:/var/lib/jenkins/.rvm/gems/jruby-1.7.19/bin:/var/lib/jenkins/.rvm/gems/jruby-1.7.19@global/bin:/var/lib/jenkins/.rvm/rubies/jruby-1.7.19/bin:/var/lib/jenkins/Sikuli-X-1.0rc3-linux-x86_64/Sikuli-IDE:/var/lib/jenkins/Sikuli-X-1.0rc3-linux-x86_64/Sikuli-IDE/libs

#~/sikuli/sikuli/runIDE -r first.sikuli

#the following line loads RVM into the shell "as a function"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

cd second.sikuli
cucumber
